/**
 * AgriDPIPayload — public L4 advisory response.
 * Section 5, Engineering Handbook v2.
 *
 * This is the shape served by the DPI gateway's /api/v1/advisory/regenerative
 * endpoint (Section 8). It bundles raw spatial data with the deterministic
 * recommendation and the Gemini narration of that recommendation.
 *
 * @see Section 5  — Canonical Data Models
 * @see Section 6  — Data Integrity Rule
 * @see Section 8  — Layer 4 API Contract
 */

import { RecommendationCandidate } from './recommendation-candidate.js';

/**
 * Soil chemistry metrics retrieved from ISRIC SoilGrids REST API.
 *
 * Source: ISRIC SoilGrids REST API (Section 6, Section 11).
 */
export interface SoilMetrics {
  /** Source: ISRIC SoilGrids REST API */
  ph_level: number;

  /** Source: ISRIC SoilGrids REST API */
  organic_carbon_percentage: number;

  /** Source: ISRIC SoilGrids REST API */
  texture_classification: string;
}

/**
 * Remote sensing data from Google Earth Engine / Sentinel-2.
 *
 * Source: Google Earth Engine, Sentinel-2 band math (Section 6, Section 11).
 */
export interface RemoteSensing {
  /** Source: Google Earth Engine, Sentinel-2 band math */
  sentinel2_ndvi_mean: number;
}

export interface AgriDPIPayload {
  /**
   * ISO 8601 timestamp of when the advisory was generated.
   */
  timestamp: string;

  /**
   * Location of the advisory request.
   */
  location: {
    latitude: number;
    longitude: number;
  };

  /**
   * Soil chemistry data for the requested location.
   *
   * Source: ISRIC SoilGrids REST API (Section 6).
   */
  soil_metrics: SoilMetrics;

  /**
   * Satellite remote sensing data for the requested location.
   *
   * Source: Google Earth Engine, Sentinel-2 band math (Section 6).
   */
  remote_sensing: RemoteSensing;

  /**
   * The deterministic recommendation computed by L2a rules engine.
   *
   * Source: Derived — L2a rules engine output, Section 4.2.
   */
  regenerative_plan: RecommendationCandidate;

  /**
   * Human-readable narration of regenerative_plan in the farmer's language.
   * Generated by Gemini (L2b) using the narrate-only prompt (Section 10.1).
   *
   * Source: Gemini narration of an already-computed RecommendationCandidate
   *         — never a source of new facts (Section 6).
   */
  explanation_text: string;
}
